### ISSUE TITLE
Arcemu based Scripts don't work

### ISSUE THREAD

**Issue by Nupper** [AscEmu/AscEmu#201]
I have tried all my old scripts and none of them seem to work.
even simple scripts.

I did mention when i joined i would like to of been able to still use my old scripts...but it seems i need to get used to new things again.

**Comment by Zyres** [comment]
Hi Nupper
I don't really know why this is a issue here at "AscEmu". Also I don't know what scripts don't work...
This issue is closed because we don't care about arcemu scripts and we don't support old and dead projects.
If you have some specific problems with a script, use our forums (I already saw you opened a thread related to this issue)
