### ISSUE TITLE
Creatures doing a little "wait step" on reaching wp

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#228]
Creatures on a wp-path doing a little "wait step" on reaching a waypoint.
Set the walk animation if an npc is on a waypoint path until it is interacting with an player or reaching its end.

**Comment by armm77** [comment]
This failure also have seen, and in my opinion is related to the cells where the character is located, if the character is in the same cell as the creature, the creature walks, otherwise it remains static until a character enters to his cell. This also affects the zeppelin and boats. I compared our emulator with cmangos and trinity, and they activate large maps or more cells, also ships and zeppelin, so this is not any character are working near active areas. I hope to make myself understood.

**Comment by aaron02** [comment]
Maybe we should activate more than only 1 ore 2 cells i think it would be better to activate all cells in a zone or in a larger area i think this affects wintergrasp too because wen are to far away from the walls they dont spawn and you cant shoot them  until you are close ensught

**Comment by armm77** [comment]
Wintergrasp, will be analyzed either because the battle lasts just 30 min at that time should be all the active zone, and at the end of the battle only the cells that need it. Otherwise the towers only update their state when some mint character, as also happens to creatures.

**Comment by Zyres** [comment]
@armm77 no, the issue you described has nothing to do with my basic issue.... it is not even related to it. So please open a new issue with your description.

**Comment by Zyres** [comment]
Since movement/spilne packets are handled in a proper way, the walking creatures turning to a 0 orientation on reaching a wp.
