### ISSUE TITLE
valgrind log #1

### ISSUE THREAD

**Issue by Lectro** [AscEmu/AscEmu#291]
build info: build debug x64, atergos os x64 (updated to 2016-03-10)
core rev: https://github.com/AscEmu/AscEmu/commit/d8a0538387bf56f6c2870b0508848a8298bb68fc
compiler: clang 3.7.0 compiler was used
database server: mariadb
database: official ascemu database with sql updates from ascemu branch

Valgrind options: 
--tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes

This was tested without any players or any other calls, just server startup

https://gist.github.com/Lectro/95fcd670ba66ccb00527

**Comment by Zyres** [comment]
I'm not sure if it is an issue or not. The process of optimizing the code base is more an improvement than an actual issue. It is the same for coverity-scan. Otherwise we have to submit all these "errors" to the github issue tracker in a more "detailed" form (for every error in valgrind/coverity one issue in github).
I'm open for a discussion about this topic.

**Comment by Zyres** [comment]
As I said, I'm open for a discussion how we would track these "issues". Currently all static analysis reports are not handled in the github issue tracker.
