### ISSUE TITLE
Naked players (rare visual bug)

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#507]
According to @Appled: there is a visual bug on player login in. It is common around emus and blizzard, that items are missing (visual) for other player.
NOTE: Check inventory fields/update. Maybe these information gets lost between login and fulli logged in.
NOTE II: Check if it is possible to update item slots for other players, if not change the position when it gets updated/send to online players.
NOTE III: Latency may cause this too....

**Comment by Appled** [comment]
I was going to create the issue soonish xd
anyways, I'll try to get some screenshots soon(ish).

**Comment by Appled** [comment]
from TC: https://github.com/TrinityCore/TrinityCore/issues/15159
from wotlk retail: http://www.mmo-champion.com/threads/636939-Naked-Bug
probably not fixable, can be a client issue

**Comment by Appled** [comment]
I get this reproduced everytime like this:
- Have 2 clients and 2 accounts.
- Log in with client A, create new human character. Let's call this clientA.
- Log in with client B, create new human character. Let's call this clientB.
- If on client B, the client A is not naked, try relogging. For client A, because it first logged in, client B shouldn't be naked at any point.
- I get it 100% reproduced if I have already two characters at same location, it didn't happen when I created new characters and logged in.

So when you login, it seems like on push to the world, it doesn't correctly update already logged in players' items.

**Comment by Zyres** [comment]
We could try a lot of things but if the client fucks up the visual appearance there is nothing we can do. As mentioned in the referenced issue it is in fact normal behavior (retail). Closed for now.

**Comment by CyberMist2** [comment]
Can we use easy-hack fixes? Such as the very well known spell 54844 Add Aura and Remove aura behaviours on:
- Player Login
- On Zone Update
- On Map Change

Probably this can help at least with the idea when it happens (on login, zone update, map change)

**Comment by opicron** [comment]
I can confirm that cleaning the client cache fixed this. I kept seeing a character without gear. Cleaned my cache and fixed. I tried Add Aura and Remove Aura as described above-- but that did not fix the issue.

**Comment by Zyres** [comment]
As already stated, it is "blizzlike" and we are not able to modify the client data (we do only serverside stuff here). We already worked on update and the datastructure. This issue is closed for now.
