### ISSUE TITLE
DB Versioning and auto update

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#541]
**Description**:  
Since we support different versions, we have to provide a solution for db versioning. We discussed already some possible solutions.

**Steps to close this issue**:

- [x] Base DB (upload on github?)
- [x] Auto update system
- - [x] Documentation
- - [x] Basic set up in branch
- [x] Versioning of current state and clean cata updates

**Comment by Zyres** [comment]
#484

**Comment by brotalnia** [comment]
I am not sure this is what you need, but I can explain how I designed the progression system on elysium / lights hope (mangos based emu), and maybe it will be useful to you. The progression system is meant to implement all changes to content through the patches of vanilla, so that we can have an item for example be in the correct state for patch 1.9 or whatever we are currently running.

All data is in the same database, but it is marked with a patch value. The patch is a column in each table, and it is part of the primary key along with the ID of the entry. It indicates when this particular version of the item (or whatever) was added. There can be multiple entries for one item, each with a different patch value. New entries for the same item are only added for the patches where it changed.

Example:
If an item was first added in patch 1.0, then later changed in patch 1.2, you would have 2 entries of it in the database, each entry marked with the patch in which this particular version was added.

![patches](https://user-images.githubusercontent.com/6519171/36529231-6746e82a-17c0-11e8-9c9a-7437fb0bfd8c.jpg)


Then at startup the core loads the entry with the highest patch value that is not above the current patch for the realm set in the config file. This is the query that accomplishes it:

`WorldDatabase.PQuery("SELECT MAX(%s) FROM %s t1 WHERE patch=(SELECT max(patch) FROM %s t2 WHERE t1.%s=t2.%s && patch <= %u)", store.EntryFieldName(), store.GetTableName(), store.GetTableName(), store.EntryFieldName(), store.EntryFieldName(), current_patch);`

Since this is done in the query that loads the data from the database at startup, there is no runtime cost.

Doing it this way will allow you to use the same database for all expansion. Since AscEmu tries to support 4 expansion in the same core, this seems very beneficial to me. You won't have to manage 4 separate databases and port fixes from one db to the other. For things like items, creatures, gameobjects, you can automate the patch assignment based on does the display Id exist in the appropriate client.

**Comment by Zyres** [comment]
We already work on a poc for the wow data, but I appreciate that you share your work with us.

I wonder, how can you know in your example which items gets removed?

This issue is about the internal versioning of the database. We have to make sure that the latest core uses the latest database (we do already but not in a good to support autoupdates). The database has its own version (e.g. AscEmu-DB 5.15). As soon as there is some automated process, we can work on the database itself and the wow versions.

**Comment by Appled** [comment]
@brotalnia This is definitely one way to do this, and could be the easiest way for creature, item and quest data without having multiple databases or tables for each expansion. But oh boy it will get very complex with loots and spawns (Dustwallow March in 2.3 patch, Stormwind Harbor and all new zeppelin towers in 3.0 patch, and whole world redone in 4.0 patch etc).

**Comment by brotalnia** [comment]
> I wonder, how can you know in your example which items gets removed?

The templates (prototypes) themselves do not get removed. On retail if you had previously gotten some item that was later removed in an expansion, you still have it in your inventory, the item exists, but it is simply unobtainable now. The single patch value is only used for the `*_template` tables, since the templates (prototypes) are never removed. It only needs to go in one direction.

For things like loot drops or creature spawns, we use a `patch_min` and `patch_max` column. Those are not keys like the `patch` column in the `*_template` tables. So if a creature's spawn position changed in a patch, you would have 2 separate spawns for it with different guids, but appropriate minimum and maximum patch values assigned so only one will be loaded based on the current patch.

![loot](https://user-images.githubusercontent.com/6519171/36557417-dbf04522-1810-11e8-8092-b7f96d497aac.jpg)

^ This is an example from the loot table. If an item was made unobtainable in patch 1.7 for example, you would simply change the patch_max value to that and it won't drop after this patch.

If you already have a separate database for each expansion btw, you could write some tool to compare all the tables, and assign patches to entries that do not exist (or have a different value in some column) in the database for the previous expansion. I can see it being problematic in Cataclysm though, as they changed the whole world.

**Comment by Zyres** [comment]
I created already a poc for this, just for templatey but sure we already know how we could deal with different content: https://github.com/Zyres/AE_OneDB (not maintained since I just wanted to create a proof of concept)...

I would tend to seperated spawn tables at least for cataclysm... but we will see if we are working on it.

**Comment by Zyres** [comment]
First step is done. The DB can be found here: https://github.com/AscEmu/OneDB

**Comment by Zyres** [comment]
Done https://ascemu.github.io/Wiki/docs/unsorted/auto_update/
