### ISSUE TITLE
Remove account flags from account table

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu#620]
**Description**:  
There is no reason to keep the account flags since a account can connect to realmlist which shows the supported realm for the client version.

**Comment by RAlexis** [comment]
Actually, there is. I mean, people on retail can have every expansion except BfA, so they can play until 110 and not further. How else do you check which expansion does the user have if not through those flags? I know probably no one uses this in the private scene, but I'm just saying.

**Comment by Zyres** [comment]
The server knows the build version of the client: https://github.com/AscEmu/AscEmu/blob/master/src/logonserver/Auth/AuthSocket.Legacy.cpp#L122

So we already know which expansion the user have based on the client he/she/... tries to connect.

**Comment by Appled** [comment]
He means that in retail you can use bfa client but your account doesn't need to be associated with bfa. I remember back in tbc before I got tbc for my account, I could play around with tbc client but I could not access tbc content, such as outlands etc.
But I do agree that the flags are not used and not required in private server scene.

**Comment by schnek** [comment]
this is a good idea. You need a "build_version" system for content that can be done through the database. (already implemented)

**Comment by schnek** [comment]
https://github.com/AscEmu/AscEmu/commit/b3fe95f7126ab0d9eec3d1810cbe45c9b0722f42 this decision should be temporary

**Comment by brotalnia** [comment]
Are you guys discussing the purpose of the account addon level (allowed expansions flag)? That does have a function. It impacts the game in several ways.

- Gating content:

If you only have the vanilla game (addon level 0), then you won't be able to create Blood Elves, Draenei, Death Knights, Worgen and Goblin on a TBC/Wotlk/Cataclysm server. The client will disable the buttons. Also it prevents you from going to any of the expansion zones, and you can't level up past 60. This can be useful for a twinking server, or for releasing content progressively (going through the content of the expansions in order, but on the same client and server version).

- Using a smaller client:

At least on TBC and WotLK, I know that you can login to an account with addon = 0 even without having the expansion data, thus being able to use a much smaller client (only updating the vanilla client with the patches to 2.4.3 for example, but not installing the TBC expansion from the disk). If you tried the same on an account with addon != 0, you would get a login error saying you need to install the expansion to play.

- Being able to play in the normal BG bracket while having your experience disabled:

On retail servers during WotLK and Cataclysm, if you disabled your experience gain, you would be put into a separate battlegrounds queue only with other people who did the same. You could not play in the normal bracket if you disabled your XP from the NPC. In most battlegroups that meant you would never get into any BGs on your level 60/70/80 twink, as there weren't enough people. And if you enabled your XP in order to play in the normal bracket, you would eventually level up because battlegrounds give experience in WotLK and Cataclysm, thus your twink would be ruined.

HOWEVER, accounts that are limited to a certain level because they don't have the expansion are special! If you only had the vanilla game, you would not be able to level up past level 60, BUT you would still get put into the normal battleground queue. I know people who bought a second account but didn't purchase the latest expansion, so that they could twink on level 60/70/80 and get fast BG queues playing in the normal leveling bracket.

- Being able to queue for old dungeons at a higher level:

In WotLK and Cataclysm, the option to queue for a "Random Classic Dungeon" is removed at level 58, at which point it is replaced by the "Random TBC Normal" option. This sucks a lot for level 60 twinks, as you can't use the dungeon finder to do vanilla content at level 60. However, if your account has only the vanilla game active (addon = 0), you would be able to queue for a "Random Classic Dungeon" past level 58!

**Comment by Zyres** [comment]
@brotalnia have a look at my comment on 27. Aug.
the only valid point is to disable experience gain which is not part of the account flag, at least on our side.

**Comment by Zyres** [comment]
We will keep the account flags, proposal is closed for now.

**Comment by Zyres** [comment]
Back to this proposal.

I get it that some players want to controle their level cap or if they gain experience.

In a multiversion projekt like this, the account flag is just pure pain. Sure you can switch the game version by simply recompile the core. You keep all your chars, items etc. The complete project is mostly serialised except the acount flag.

I guess people on retail use the accountoptions on the blizzard web pages to set up some options.

Speaking of options, AE requires the accountflags so I have to set the highes flag for the current version instead of setting the flag if I want to.

The AE logonserver can manager world server with different client versions (tbc, wotlk and cata) if you set up your account for a tbc server you have to change the account flag if you want to play on a  cata server. It makes no sense to set the account flag global in this setting.

So I would still suggest to remove the global accountflag from table account and set up a seperate table to set up the account flag for a specific server or at least for a specific client version.
